export interface Env { DB?: D1Database; REPORTS_BUCKET?: R2Bucket; JOB_QUEUE?: Queue; GPT_ACTION_TOKEN?: string; APP_ENV?: string; ALLOW_LIVE_TRADING?: string; APPROVAL_REQUIRED?: string }
type Scenario = 'real_estate' | 'resale' | 'trading_sim' | 'crypto_sim' | 'all';
type RunRequest = { scenario: Scenario; dryRun?: boolean; notes?: string; filters?: Record<string, unknown>; live?: boolean };
type ReportItem = { id: string; jobId: string; scenario: Scenario; title: string; score: number; summary: string; metrics: Record<string, string | number | boolean>; createdAt: string };
const sampleStore: ReportItem[] = [];
const id = (p: string) => `${p}_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
const now = () => new Date().toISOString();
const j = (data: unknown, status = 200) => new Response(JSON.stringify(data, null, 2), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-allow-headers': 'authorization,content-type' } });
function authorized(req: Request, env: Env) { return !env.GPT_ACTION_TOKEN || req.headers.get('authorization') === `Bearer ${env.GPT_ACTION_TOKEN}`; }
function safe(body: RunRequest, env: Env) { if ((body.live || body.dryRun === false) && env.ALLOW_LIVE_TRADING !== 'true') throw new Error('Live execution is disabled. Use dryRun=true or configure risk controls first.'); }
function items(jobId: string, scenario: Scenario, dryRun: boolean): ReportItem[] { const createdAt = now(); if (scenario === 'real_estate') return [{ id:id('item'), jobId, scenario, title:'駅徒歩8分・築浅区分マンション候補', score:82, summary:'想定利回りと駅距離のバランスが良い。管理費と修繕積立金の追加確認が必要。', metrics:{ estimatedYield:'5.4%', priceGap:'-6%', stationWalkMin:8, dryRun }, createdAt }, { id:id('item'), jobId, scenario, title:'郊外ファミリー向け戸建て候補', score:71, summary:'価格は割安だが空室期間リスクがやや高い。周辺成約事例の確認が必要。', metrics:{ estimatedYield:'6.1%', vacancyRisk:'medium', priceGap:'-9%', dryRun }, createdAt }]; if (scenario === 'resale') return [{ id:id('item'), jobId, scenario, title:'小型家電カテゴリ候補', score:78, summary:'粗利率は高いが、在庫回転と返品率の確認が必要。', metrics:{ grossMargin:'22%', estimatedProfit:1800, feeRate:'12%', dryRun }, createdAt }, { id:id('item'), jobId, scenario, title:'季節用品カテゴリ候補', score:69, summary:'季節性が強いため、仕入れ数量を抑えた検証向き。', metrics:{ grossMargin:'18%', seasonality:'high', estimatedProfit:950, dryRun }, createdAt }]; return [{ id:id('item'), jobId, scenario, title: scenario === 'crypto_sim' ? '暗号資産トレンド戦略シミュレーション' : '株式モメンタム戦略シミュレーション', score:74, summary:'バックテスト上はプラスだが、最大ドローダウンと取引コストに注意。ライブ取引は無効。', metrics:{ returnPct:'8.2%', maxDrawdown:'-6.8%', winRate:'54%', liveTrading:false, dryRun }, createdAt }]; }
export async function runScenario(body: RunRequest, env: Env) { safe(body, env); const jobId = id('job'); const dryRun = body.dryRun !== false; const scenarios: Scenario[] = body.scenario === 'all' ? ['real_estate','resale','trading_sim','crypto_sim'] : [body.scenario]; const report = scenarios.flatMap(s => items(jobId, s, dryRun)); sampleStore.unshift(...report); if (env.DB) { await env.DB.prepare('CREATE TABLE IF NOT EXISTS report_items (id TEXT PRIMARY KEY, job_id TEXT, scenario TEXT, title TEXT, score REAL, summary TEXT, metrics_json TEXT, created_at TEXT)').run(); for (const it of report) await env.DB.prepare('INSERT INTO report_items VALUES (?1,?2,?3,?4,?5,?6,?7,?8)').bind(it.id,it.jobId,it.scenario,it.title,it.score,it.summary,JSON.stringify(it.metrics),it.createdAt).run(); } return { jobId, scenario: body.scenario, dryRun, message: dryRun ? 'Dry run completed. Replace sample connectors with approved data APIs for production.' : 'Live execution completed under configured safety controls.', items: report }; }
async function latest(env: Env): Promise<ReportItem[]> { if (!env.DB) return sampleStore.length ? sampleStore.slice(0,50) : items('local_sample','real_estate',true).concat(items('local_sample','resale',true), items('local_sample','trading_sim',true)); try { const r = await env.DB.prepare('SELECT id, job_id as jobId, scenario, title, score, summary, metrics_json as metricsJson, created_at as createdAt FROM report_items ORDER BY created_at DESC LIMIT 50').all<any>(); return (r.results || []).map(row => ({ id:row.id, jobId:row.jobId, scenario:row.scenario, title:row.title, score:row.score, summary:row.summary, metrics:JSON.parse(row.metricsJson||'{}'), createdAt:row.createdAt })); } catch { return sampleStore.length ? sampleStore.slice(0,50) : items('local_sample','real_estate',true); } }
function csv(rows: ReportItem[]) { const esc = (v:string) => /[",\n]/.test(v) ? `"${v.replaceAll('"','""')}"` : v; return [['createdAt','scenario','title','score','summary','metrics'], ...rows.map(x=>[x.createdAt,x.scenario,x.title,String(x.score),x.summary,JSON.stringify(x.metrics)])].map(r=>r.map(esc).join(',')).join('\n') + '\n'; }
function html(rows: ReportItem[]) { const trs = rows.map(x=>`<tr><td>${x.scenario}</td><td>${x.title}</td><td><b>${x.score}</b></td><td>${x.summary}</td></tr>`).join(''); return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GitHub Full Automation</title><style>body{font-family:system-ui;background:#f8fafc;color:#0f172a;margin:0}header{background:#0f172a;color:white;padding:28px}.wrap{max-width:1100px;margin:auto;padding:24px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card,table{background:white;border:1px solid #e2e8f0;border-radius:16px;padding:16px;box-shadow:0 8px 22px #0f172a12}button,a{background:#2563eb;color:white;border:0;border-radius:10px;padding:10px 14px;text-decoration:none;margin:4px;display:inline-block}table{width:100%;border-collapse:collapse;margin-top:18px}td,th{border-bottom:1px solid #e2e8f0;text-align:left;padding:12px}.log{white-space:pre-wrap;background:#0f172a;color:#d1fae5;border-radius:12px;padding:14px;margin-top:16px}</style></head><body><header><div class="wrap"><h1>GitHub Full Automation</h1><p>Custom GPT / GitHub Actions / Cloudflare による自動化テンプレート</p></div></header><main class="wrap"><section class="cards"><div class="card"><h2>不動産</h2><button data-scenario="real_estate">更新</button></div><div class="card"><h2>物販</h2><button data-scenario="resale">更新</button></div><div class="card"><h2>投資シミュレーション</h2><button data-scenario="trading_sim">更新</button></div></section><p><button data-scenario="all">全部更新</button><a href="/api/export.csv">Excel用CSV</a></p><h2>最新レポート</h2><table aria-label="latest reports"><thead><tr><th>種類</th><th>タイトル</th><th>スコア</th><th>概要</th></tr></thead><tbody>${trs}</tbody></table><div id="log" class="log">Ready.</div></main><script>document.querySelectorAll('button[data-scenario]').forEach(b=>b.onclick=async()=>{log.textContent='Running '+b.dataset.scenario;const r=await fetch('/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scenario:b.dataset.scenario,dryRun:true})});log.textContent=JSON.stringify(await r.json(),null,2);setTimeout(()=>location.reload(),1000);});</script></body></html>`; }
export default { async fetch(req: Request, env: Env): Promise<Response> { if (req.method === 'OPTIONS') return j({ok:true}); const url = new URL(req.url); try { if (url.pathname === '/') return new Response(html(await latest(env)), { headers:{'content-type':'text/html; charset=utf-8'} }); if (url.pathname === '/api/health') return j({ok:true, service:'github-full-automation', env:env.APP_ENV || 'unknown', time:now()}); if (url.pathname === '/api/report') return j({ok:true, generatedAt:now(), reports:await latest(env)}); if (url.pathname === '/api/export.csv') return new Response(csv(await latest(env)), { headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="automation-report.csv"'} }); if (url.pathname === '/api/run' && req.method === 'POST') { if (!authorized(req, env)) return j({ok:false,error:'Unauthorized'},401); return j({ok:true, ...(await runScenario(await req.json<RunRequest>(), env))}); } return j({ok:false,error:'Not found'},404); } catch (e) { return j({ok:false,error:e instanceof Error ? e.message : 'Unknown error'},500); } }, async scheduled(_event: ScheduledEvent, env: Env, ctx: ExecutionContext) { ctx.waitUntil(runScenario({scenario:'all', dryRun:true, notes:'cron refresh'}, env)); } };
